# Generated by Django 5.0.4 on 2024-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('discription', models.CharField(max_length=200)),
                ('publishdate', models.DateField()),
            ],
        ),
    ]
